FROM node:16-alpine

# dodano, ker so bile tezave z node_modules direktorijem
RUN mkdir /app && chown node:node /app
WORKDIR '/app'

USER node

COPY --chown=node:node package.json package-lock.json* ./
RUN npm install

COPY --chown=node:node . .

CMD ["npm", "run", "start"]